import { type NextPage } from "next";
import Head from "next/head";
import { Link, LinkProps } from "@fluentui/react-components";

const Home: NextPage = (props: LinkProps & { as?: "a"}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <div className="flex justify-center py-4" id="header">
          <ul className="flex space-x-4" id="nav">
            <li><Link href="#" {...props}>Home</Link></li>
            <li><Link href="#" {...props}>About</Link></li>
            <li><Link href="#" {...props}>Contact</Link></li>
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
